GET http://localhost:3000/band/details
Content-Type: application/json

{
    "id": "",
    "name": ""
}

###

POST http://localhost:3000/show/create
Content-Type: application/json

{
    "week_day": "sabado",
    "start_time": 8,
    "end_time": 9,
    "band_id": "789123"
}

###

GET http://localhost:3000/show/details
Content-Type: application/json

{
    "week_day": "sabado"
}


####

POST http://localhost:3000/user/signup/
Content-Type: application/json

{
    "name": "Kurt Cobain",
    "email": "kurt@nirvana.com",
    "password": "axlsucks",
    "role": "ADMIN"
}

###

GET http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "kurt@nirvana.com",
    "password": "axlsucks"
}