GET http://localhost:3000/band/details
Content-Type: application/json

{
    "id": "",
    "name": ""
}

###

POST http://localhost:3000/show/create
Content-Type: application/json

{
    "week_day": "sexta",
    "start_time": 11,
    "end_time": 12,
    "band_id": "789123"
}

###

GET http://localhost:3000/show/details
Content-Type: application/json

{
    "week_day": "sabado"
}
